// Static fallback data used when MongoDB is not connected.
// This allows the site to render a full product catalogue for demos.

export type FallbackCategory = {
  _id: string;
  name: string;
  slug: string;
  description: string;
  sortOrder: number;
};

export type FallbackProduct = {
  _id: string;
  name: string;
  slug: string;
  sku: string;
  description: string;
  category: FallbackCategory;
  specifications: Record<string, string>;
  useCases: string[];
  isFeatured: boolean;
  isActive: boolean;
  image?: string;
  cataloguePage?: string;
};

export const fallbackCategories: FallbackCategory[] = [
  { _id: "cat-1", name: "Cable Ties", slug: "cable-ties", description: "Nylon and stainless steel cable ties for bundling and securing cables in all environments.", sortOrder: 1 },
  { _id: "cat-2", name: "Heat Shrink Tubing", slug: "heat-shrink-tubing", description: "Polyolefin and specialty heat shrink tubing for insulation, protection, and colour coding.", sortOrder: 2 },
  { _id: "cat-3", name: "Cable Markers", slug: "cable-markers", description: "Clip-on, slide-on, and wrap-around cable markers for circuit and cable identification.", sortOrder: 3 },
  { _id: "cat-4", name: "Ferrules & Terminals", slug: "ferrules", description: "Insulated and uninsulated wire end ferrules, copper lugs, aluminium terminals, and XLPE connectors.", sortOrder: 4 },
  { _id: "cat-5", name: "Cable Glands", slug: "cable-glands", description: "IP-rated cable glands for secure cable entry into enclosures, junction boxes, and panels.", sortOrder: 5 },
  { _id: "cat-6", name: "Identification Labels", slug: "identification-labels", description: "Self-laminating, thermal, and pre-printed labels for permanent cable and asset identification.", sortOrder: 6 },
  { _id: "cat-7", name: "Cable Management", slug: "cable-management", description: "DIN rails, trunking, conduit pipe, and cable management accessories for professional installations.", sortOrder: 7 },
  { _id: "cat-8", name: "Tapes & Insulation", slug: "tapes-insulation", description: "Self-amalgamating, cloth, and vinyl insulation tapes for electrical protection and waterproofing.", sortOrder: 8 },
  { _id: "cat-9", name: "Cable Sleeving & Tubing", slug: "cable-sleeving", description: "Woven sleeving, spiral binding, and flexible corrugated tubing for cable protection and organisation.", sortOrder: 9 },
  { _id: "cat-10", name: "Connectors & Strips", slug: "connectors", description: "Connector strips, push-in connectors, and line taps for quick and reliable electrical connections.", sortOrder: 10 },
  { _id: "cat-11", name: "Wiring Accessories", slug: "wiring-accessories", description: "Grommets, snap bushings, blanking plugs, saddle supports, and cable mounting accessories.", sortOrder: 11 },
  { _id: "cat-12", name: "Stainless Steel Fixings", slug: "stainless-steel", description: "304 stainless steel cable ties, banding straps, and buckles for harsh and outdoor environments.", sortOrder: 12 },
];

export const fallbackProducts: FallbackProduct[] = [
  {
    _id: "prod-1",
    name: "Nylon Cable Tie 200mm x 4.8mm",
    slug: "nylon-cable-tie-200mm",
    sku: "CT-NYL-200",
    description: "General purpose UV-resistant nylon 66 cable ties. Suitable for indoor and outdoor applications. Self-locking mechanism provides secure cable bundling for electrical, data, and general wiring installations.",
    category: fallbackCategories[0],
    specifications: { Material: "Nylon 66 (PA66)", Length: "200mm", Width: "4.8mm", "Tensile Strength": "22kg", Colour: "Black / Natural", "Operating Temp": "-40°C to +85°C", "Flammability Rating": "UL94 V-2" },
    useCases: ["Panel wiring and cable bundling", "Outdoor cable installations", "Temporary and permanent cable management", "HVAC duct and pipe fastening"],
    isFeatured: true,
    isActive: true,
    image: "/products/cable-ties-nylon.png",
  },
  {
    _id: "prod-2",
    name: "Heavy Duty Cable Tie 370mm x 7.6mm",
    slug: "heavy-duty-cable-tie-370mm",
    sku: "CT-HD-370",
    description: "Heavy-duty UV-stabilised cable ties for demanding industrial applications. High tensile strength makes them ideal for mining, construction, and outdoor infrastructure projects where reliability is critical.",
    category: fallbackCategories[0],
    specifications: { Material: "Nylon 66 (PA66)", Length: "370mm", Width: "7.6mm", "Tensile Strength": "55kg", Colour: "Black", "UV Resistance": "Yes", "Operating Temp": "-40°C to +85°C" },
    useCases: ["Mining installations", "Heavy cable bundling", "Outdoor infrastructure", "Industrial panel wiring"],
    isFeatured: true,
    isActive: true,
  },
  {
    _id: "prod-3",
    name: "Polyolefin Heat Shrink Tubing Kit",
    slug: "heat-shrink-tubing-kit",
    sku: "HS-KIT-001",
    description: "Multi-size polyolefin heat shrink assortment kit containing common sizes for electrical insulation, wire protection, and colour-coded cable identification. 2:1 shrink ratio with excellent dielectric properties.",
    category: fallbackCategories[1],
    specifications: { Material: "Polyolefin", "Shrink Ratio": "2:1", "Sizes Included": "1.5mm to 12mm", Colours: "Black, Red, Blue, Green, Yellow, Clear", "Operating Temp": "-55°C to +125°C", "Dielectric Strength": ">15kV/mm" },
    useCases: ["Wire insulation and protection", "Colour-coded cable identification", "Solder joint protection", "Component strain relief"],
    isFeatured: true,
    isActive: true,
  },
  {
    _id: "prod-4",
    name: "Dual Wall Heat Shrink with Adhesive",
    slug: "dual-wall-heat-shrink-adhesive",
    sku: "HS-DW-3-1",
    description: "Dual wall heat shrink tubing with internal adhesive liner. Provides a waterproof seal when heated, making it ideal for outdoor and underground cable joints and terminations.",
    category: fallbackCategories[1],
    specifications: { Material: "Polyolefin with adhesive liner", "Shrink Ratio": "3:1", "Sizes Available": "3mm to 50mm", Colour: "Black", "Waterproof Rating": "IP68 when applied", "Operating Temp": "-55°C to +125°C" },
    useCases: ["Waterproof cable joints", "Underground cable protection", "Marine and outdoor wiring", "Corrosion protection on terminations"],
    isFeatured: false,
    isActive: true,
  },
  {
    _id: "prod-5",
    name: "Clip-On Cable Markers (0-9)",
    slug: "clip-on-cable-markers-0-9",
    sku: "CM-CLIP-09",
    description: "Pre-printed clip-on cable markers numbered 0 to 9 for quick and clear cable identification. Snap-on design allows installation on existing cables without disconnection.",
    category: fallbackCategories[2],
    specifications: { Material: "PVC", "Print Type": "Pre-printed 0-9", "Cable Range": "1.5mm² to 6mm²", Colours: "Colour-coded per number", "Pack Size": "100 per number" },
    useCases: ["Distribution board wiring", "Circuit identification", "Panel wiring identification", "Compliance with SANS 10142"],
    isFeatured: true,
    isActive: true,
  },
  {
    _id: "prod-6",
    name: "Flat Cable Markers (A-Z)",
    slug: "flat-cable-markers-a-z",
    sku: "CM-FLAT-AZ",
    description: "Pre-printed flat profile cable markers lettered A to Z. Designed for larger cables and conduits where clip-on markers are not suitable. UV and chemical resistant.",
    category: fallbackCategories[2],
    specifications: { Material: "Polyethylene", "Print Type": "Pre-printed A-Z", "Cable Range": "4mm² to 16mm²", Colour: "Yellow with black print", "UV Resistant": "Yes" },
    useCases: ["Large cable identification", "Outdoor cable marking", "Substation cable identification", "Control panel wiring"],
    isFeatured: false,
    isActive: true,
  },
  {
    _id: "prod-7",
    name: "Insulated Bootlace Ferrules Kit",
    slug: "insulated-bootlace-ferrules-kit",
    sku: "FE-INS-KIT",
    description: "Comprehensive kit of colour-coded insulated bootlace ferrules covering the most common conductor sizes. Includes a crimping tool for professional terminal preparation.",
    category: fallbackCategories[3],
    specifications: { Material: "Copper tube with PP insulation", "Sizes Included": "0.5mm² to 16mm²", "Colour Coding": "DIN 46228 standard", "Kit Contents": "800 ferrules + crimping tool", "Barrel Type": "Seamless copper" },
    useCases: ["Switchboard wiring", "Motor control panel terminations", "PLC wiring", "Professional electrical installations"],
    isFeatured: true,
    isActive: true,
  },
  {
    _id: "prod-8",
    name: "PG13.5 Nylon Cable Gland",
    slug: "pg13-5-nylon-cable-gland",
    sku: "CG-PG13-NYL",
    description: "IP68-rated nylon cable gland with locknut for secure and waterproof cable entry into enclosures, junction boxes, and control panels. Complete with sealing washer and locknut.",
    category: fallbackCategories[4],
    specifications: { Material: "Nylon (PA66)", "Thread Size": "PG13.5", "Cable Range": "6mm to 12mm", "IP Rating": "IP68", Colour: "Grey / Black", Includes: "Locknut and sealing washer" },
    useCases: ["Junction box cable entry", "Control panel cable management", "Outdoor enclosure cable entry", "Industrial switchgear"],
    isFeatured: true,
    isActive: true,
  },
  {
    _id: "prod-9",
    name: "Brass Cable Gland 20mm",
    slug: "brass-cable-gland-20mm",
    sku: "CG-BR-20",
    description: "Nickel-plated brass cable gland for use in hazardous and demanding environments. Provides EMC screening and superior mechanical protection for cable entries.",
    category: fallbackCategories[4],
    specifications: { Material: "Nickel-plated brass", "Thread Size": "M20 x 1.5", "Cable Range": "6mm to 12mm", "IP Rating": "IP68", "EMC Screening": "Yes", "Operating Temp": "-60°C to +100°C" },
    useCases: ["Hazardous area installations", "Mining equipment", "Marine applications", "EMC-sensitive installations"],
    isFeatured: false,
    isActive: true,
  },
  {
    _id: "prod-10",
    name: "Self-Laminating Cable Labels",
    slug: "self-laminating-cable-labels",
    sku: "LB-SELF-LAM",
    description: "Self-laminating wrap-around cable labels with clear protective laminate that covers the printed area. Provides permanent, weather-resistant cable identification.",
    category: fallbackCategories[5],
    specifications: { Material: "Vinyl with clear laminate", "Print Method": "Laser or thermal transfer", "Sizes Available": "25mm x 75mm to 50mm x 150mm", "Operating Temp": "-40°C to +80°C", "UV Resistant": "Yes", Adhesive: "Permanent acrylic" },
    useCases: ["Permanent cable identification", "Outdoor cable labelling", "Data centre cabling", "Compliance labelling"],
    isFeatured: false,
    isActive: true,
  },
  {
    _id: "prod-11",
    name: "Adhesive Cable Tie Mounts",
    slug: "adhesive-cable-tie-mounts",
    sku: "CMA-ADH-25",
    description: "Self-adhesive cable tie mounting bases for securing cable runs to flat surfaces. Strong acrylic adhesive pad bonds to metal, plastic, and painted surfaces.",
    category: fallbackCategories[6],
    specifications: { Material: "Nylon (PA66)", "Base Size": "25mm x 25mm", "Tie Width": "Up to 4.8mm", Adhesive: "Acrylic foam", Colour: "White / Black", "Pack Size": "100 pieces" },
    useCases: ["Cable routing on panels", "Desktop cable management", "Wall-mounted cable runs", "Cable tray accessories"],
    isFeatured: false,
    isActive: true,
  },
  {
    _id: "prod-12",
    name: "Spiral Cable Wrap 12mm",
    slug: "spiral-cable-wrap-12mm",
    sku: "CMA-SPR-12",
    description: "Flexible polyethylene spiral wrap for bundling and protecting cable harnesses. Easy to install and remove, allowing addition or removal of cables at any point.",
    category: fallbackCategories[6],
    specifications: { Material: "Polyethylene (PE)", "Wrap Diameter": "12mm", "Bundle Range": "10mm to 100mm", Colour: "Black / Natural", "Roll Length": "10m", "Operating Temp": "-50°C to +100°C" },
    useCases: ["Cable harness bundling", "Workstation cable management", "Automotive wiring protection", "Machine cable protection"],
    isFeatured: false,
    isActive: true,
  },

  // --- CABLE MANAGEMENT ---
  {
    _id: "prod-13",
    name: "DIN Rails",
    slug: "din-rails",
    sku: "DIN-RAIL",
    description: "HEX brand steel DIN rails available in slotted, plain dotted, and plain profiles. 35 x 7.5mm galvanised steel construction, RoHS compliant. Ideal for mounting circuit breakers, relays, and terminal blocks in control panels.",
    category: fallbackCategories[6],
    specifications: { Type: "Slotted / Plain Dotted / Plain", Size: "35 x 7.5mm", Material: "Steel galvanised (white passivated)", Compliance: "RoHS compliant", Length: "2000mm" },
    useCases: ["Control panel DIN rail mounting", "Distribution boards", "Industrial automation enclosures", "MCB and relay mounting"],
    isFeatured: false,
    isActive: true,
    image: "/products/din-rails.png",
    cataloguePage: "/products/pages/catalogue-04.png",
  },
  {
    _id: "prod-14",
    name: "Trunking - Narrow Slot",
    slug: "trunking-narrow-slot",
    sku: "TRUNK-NS",
    description: "PVC narrow slot trunking for neat and professional cable management. Available in a wide range of sizes from 25x25mm to 100x60mm. Features tight-fitting lids and self-extinguishing UL 94 V-0 material. Temperature rated -10°C to +60°C.",
    category: fallbackCategories[6],
    specifications: { Material: "Rigid Flame Free PVC", Colour: "Grey", "UL Rating": "94 V-0 Self-extinguishing", "Temperature Rating": "-10°C to +60°C", Length: "2000mm", "Size Range": "25x25mm to 100x60mm" },
    useCases: ["Control panel cable management", "Distribution board wiring", "Machine cable routing", "Panel building"],
    isFeatured: false,
    isActive: true,
    image: "/products/trunking-slotted.png",
    cataloguePage: "/products/pages/catalogue-04.png",
  },
  {
    _id: "prod-15",
    name: "Econo Trunking Solid PVC",
    slug: "econo-trunking-solid-pvc",
    sku: "TRUNK-ECONO",
    description: "Economical solid PVC trunking for general cable management. Available in white, various sizes from 16x16mm to 100x50mm. Supplied in 3m lengths, ideal for commercial and light industrial wiring installations.",
    category: fallbackCategories[6],
    specifications: { Material: "Solid PVC", Colour: "White", "Length per Bundle": "3m", "Size Range": "16x16mm to 100x50mm" },
    useCases: ["Office cable management", "Commercial electrical installations", "Light industrial wiring", "Wall-mounted cable runs"],
    isFeatured: false,
    isActive: true,
    image: "/products/econo-trunking.png",
    cataloguePage: "/products/pages/catalogue-04.png",
  },
  {
    _id: "prod-16",
    name: "Heavy Duty Solid Trunking",
    slug: "heavy-duty-solid-trunking",
    sku: "TRUNK-HD",
    description: "Heavy duty solid PVC trunking for demanding industrial cable management. Available in white and grey, sizes from 15x10mm up to 100x100mm with cornice divider options. Chemical resistant, self-extinguishing.",
    category: fallbackCategories[6],
    specifications: { Material: "White PVC / Grey PVC", Colour: "White / Grey", "Size Range": "15x10mm to 100x100mm", "Temperature Rating": "-10°C to +60°C", Resistance: "Chemical resistant" },
    useCases: ["Industrial cable management", "Factory floor cable routing", "Heavy-duty panel wiring", "Chemical plant installations"],
    isFeatured: false,
    isActive: true,
    image: "/products/heavy-duty-trunking.png",
    cataloguePage: "/products/pages/catalogue-05.png",
  },
  {
    _id: "prod-17",
    name: "PVC Conduit Pipe",
    slug: "pvc-conduit-pipe",
    sku: "CONDUIT-PVC",
    description: "SABS-approved PVC conduit pipe for electrical wiring protection. Available in 20mm, 25mm, 32mm, and 50mm diameters, supplied in 4m lengths. Flame retardant, impact resistant, and suitable for concealed and surface wiring.",
    category: fallbackCategories[6],
    specifications: { Material: "PVC", Approval: "SABS", Sizes: "20mm, 25mm, 32mm, 50mm", Length: "4m", "Flame Rating": "Flame retardant" },
    useCases: ["Residential and commercial wiring", "Concealed conduit installations", "Surface wiring protection", "Underground conduit runs"],
    isFeatured: false,
    isActive: true,
    image: "/products/pvc-conduit-pipe.png",
    cataloguePage: "/products/pages/catalogue-05.png",
  },

  // --- CONNECTORS & STRIPS ---
  {
    _id: "prod-18",
    name: "Line Taps",
    slug: "line-taps",
    sku: "LINE-TAP",
    description: "Heavy-duty line tap connectors (HSBC range) for making tap-off connections without cutting the main conductor. Available in 16mm, 25mm, 35mm, 50mm, 70mm, and 95mm sizes.",
    category: fallbackCategories[9],
    specifications: { Range: "HSBC-16 to HSBC-95", Sizes: "16mm, 25mm, 35mm, 50mm, 70mm, 95mm", Application: "Main line tap-off connections" },
    useCases: ["Power distribution tap-offs", "Main cable connections", "Sub-distribution boards", "Overhead line tap connections"],
    isFeatured: false,
    isActive: true,
    image: "/products/line-taps.png",
    cataloguePage: "/products/pages/catalogue-05.png",
  },
  {
    _id: "prod-19",
    name: "Connector Strips",
    slug: "connector-strips",
    sku: "CONN-STRIP",
    description: "PVC insulated electrical connector strips available in 3A, 5A, 10A, 15A, 30A, 60A ratings. Available in Black and Clear, sold per strip. Suitable for domestic and light commercial electrical connections.",
    category: fallbackCategories[9],
    specifications: { Ratings: "3A, 5A, 10A, 15A, 30A, 60A", Colour: "Black / Clear", "Pack Size": "1 strip", Insulation: "PVC" },
    useCases: ["Light and power connections", "Junction box wiring", "Domestic electrical installations", "Panel wiring connections"],
    isFeatured: false,
    isActive: true,
    image: "/products/connector-strips.png",
    cataloguePage: "/products/pages/catalogue-06.png",
  },
  {
    _id: "prod-20",
    name: "Push-in Re-usable Connectors",
    slug: "push-in-reusable-connectors",
    sku: "CONN-PUSH-R",
    description: "WAGO-style push-in re-usable connectors for fast, tool-free electrical connections. Accepts solid and stranded conductors 0.2–4.0mm². CE, ENEC, UKCA, REACH, RoHS certified. Housing: Polycarbonate (PC) / Polyamide (PA). Available in 2, 3, and 5-port configurations.",
    category: fallbackCategories[9],
    specifications: { "Wire Range (Solid)": "0.2–4.0mm²", "Wire Range (Stranded)": "0.2–4.0mm²", Certification: "CE, ENEC, UKCA, REACH, RoHS", Housing: "Polycarbonate (PC) / Polyamide (PA)", "Rated Current": "32A", "Rated Voltage (IEC/EN)": "450V", Ports: "2, 3, or 5" },
    useCases: ["Fast re-usable wiring connections", "Lighting installations", "Junction boxes", "Control panel wiring"],
    isFeatured: false,
    isActive: true,
    image: "/products/push-in-reusable-connectors.png",
    cataloguePage: "/products/pages/catalogue-06.png",
  },
  {
    _id: "prod-21",
    name: "Push-in Connectors",
    slug: "push-in-connectors",
    sku: "CONN-PUSH",
    description: "Compact push-in connectors for solid wire (22–14AWG) with strip, push, and connect functionality. Available in 1–2, 1–3, 1–4, and 1–6 configurations. CE, DVE, ENEC, CQC, REACH, RoHS certified.",
    category: fallbackCategories[9],
    specifications: { "Solid Wire Range": "0.5–2.5mm² (22–14AWG)", Certification: "CE, DVE, ENEC, CQC, REACH, RoHS", "Rated Voltage (IEC/EN)": "450V", "Rated Current": "24A", Configurations: "1-2, 1-3, 1-4, 1-6" },
    useCases: ["Compact wiring connections", "LED driver connections", "Sensor wiring", "Control panel wiring"],
    isFeatured: false,
    isActive: true,
    image: "/products/push-in-connectors.png",
    cataloguePage: "/products/pages/catalogue-06.png",
  },

  // --- TAPES & INSULATION ---
  {
    _id: "prod-22",
    name: "B50 Self Amalgamating Tape",
    slug: "b50-self-amalgamating-tape",
    sku: "TAPE-B50",
    description: "EPR rubber self-amalgamating tape that bonds to itself without adhesive within hours of application. Waterproof, UV resistant, and electrically insulating. Ideal for waterproofing cable joints, corrosion protection on metal pipes, and outdoor applications.",
    category: fallbackCategories[7],
    specifications: { Material: "EPR rubber", "Dielectric Resistivity": "1x10¹⁵ Ω·cm", "Dielectric Power Factor": "3.3", "Dielectric Strength": "800 kV/mm", "Elongation at Break": "800%", Thickness: "0.75mm", Width: "18mm", "Roll Length": "3m" },
    useCases: ["Waterproofing cable joints", "Corrosion protection on pipes", "Outdoor electrical joints", "Non-slip handlebar grip"],
    isFeatured: false,
    isActive: true,
    image: "/products/b50-self-amalgamating-tape.png",
    cataloguePage: "/products/pages/catalogue-07.png",
  },
  {
    _id: "prod-23",
    name: "Cloth Tape - Coroplast 839",
    slug: "cloth-tape-coroplast-839",
    sku: "TAPE-CORO",
    description: "High-quality cloth tape (Coroplast 839) for cable bundling, wire harness wrapping, and insulation in automotive and industrial applications. Dense textile structure with solvent-free acrylic adhesive. Excellent heat resistance up to +150°C.",
    category: fallbackCategories[7],
    specifications: { Adhesive: "Solvent-free acrylic", Thickness: "0.17mm", Texture: "Rough/Smooth", "Roll Length": "25m", Colour: "Black", "Heat Resistance": "Up to +150°C (peak +185°C)" },
    useCases: ["Automotive wire harness wrapping", "Cable bundling and binding", "Vibration dampening", "High-temperature cable protection"],
    isFeatured: false,
    isActive: true,
    image: "/products/cloth-tape-coroplast.png",
    cataloguePage: "/products/pages/catalogue-07.png",
  },
  {
    _id: "prod-24",
    name: "Vinyl Tape for Electrical Insulation - Nitto #21",
    slug: "vinyl-tape-nitto-21",
    sku: "TAPE-NITTO",
    description: "Lead-free, environmentally friendly vinyl tape (Nitto No.21) for electrical insulation and colour coding. Available in 7 colours: Black, Red, Yellow, Green, Blue, White, Green/Yellow. Excellent dielectric properties, minimal flagging, easy to cut by hand.",
    category: fallbackCategories[7],
    specifications: { "Part Number": "NITTO 21-0 to 21-4S", Colours: "Black, Red, Yellow, Green, Blue, White, Green/Yellow", Thickness: "0.18mm", Width: "18mm", Length: "21yd", "Dielectric Strength": ">5000V/1 minute", "Withstand Voltage": "Add 5000V/1 minute" },
    useCases: ["Electrical insulation and colour coding", "Wire identification", "Cable wrapping", "Compliance with wiring colour codes"],
    isFeatured: false,
    isActive: true,
    image: "/products/vinyl-tape-nitto.png",
    cataloguePage: "/products/pages/catalogue-07.png",
  },

  // --- CABLE SLEEVING ---
  {
    _id: "prod-25",
    name: "Woven Sleeving",
    slug: "woven-sleeving",
    sku: "SLEEVE-WOVEN",
    description: "Polyester expandable woven sleeving that is flame retardant and halogen free. Expandable design allows the sleeve to expand up to 1.5x its initial diameter. Excellent abrasion resistance with cutting tool compatibility. Operating temperature -20°C to +150°C.",
    category: fallbackCategories[8],
    specifications: { Material: "Polyester Flammability VW-1", Colour: "Black", Certification: "UL, CSA, RoHS, PFOS, REACH, Halogen Free", "Size Range": "2mm to 60mm", "Spool Length": "30m to 500m", "Operating Temp": "-20°C to +150°C", "Melting Point": "250°C" },
    useCases: ["Cable harness protection", "Automotive wiring protection", "Industrial cable management", "Flexible conduit replacement"],
    isFeatured: false,
    isActive: true,
    image: "/products/woven-sleeving.png",
    cataloguePage: "/products/pages/catalogue-08.png",
  },
  {
    _id: "prod-26",
    name: "Spiral Binding",
    slug: "spiral-binding",
    sku: "SPIRAL-BIND",
    description: "Flexible spiral cable binding for bundling and protecting cable groups. Available in natural and black, diameter sizes from 3mm to 19mm (25m rolls). Easy to install and allows cables to be added at any point along the bundle.",
    category: fallbackCategories[8],
    specifications: { Colours: "Natural / Black", "Diameter Range": "3mm to 19mm", "Roll Length": "25m", Material: "Polyethylene" },
    useCases: ["Cable harness bundling", "Flexible hose management", "Machine cable protection", "Automotive wiring bundles"],
    isFeatured: false,
    isActive: true,
    image: "/products/spiral-binding.png",
    cataloguePage: "/products/pages/catalogue-08.png",
  },
  {
    _id: "prod-27",
    name: "MaxFlex Polypropelene Corrugated Conduit",
    slug: "maxflex-polypropelene",
    sku: "MAXFLEX-PP",
    description: "MAXFLEX flexible corrugated polypropylene conduit for protecting cables in dynamic and industrial environments. Available split or un-split for easy installation on existing cable runs. Sizes from 10x7mm to 20x15mm in black and grey.",
    category: fallbackCategories[8],
    specifications: { Material: "Polypropylene", Colours: "Black / Grey", "Size Range": "10x7mm to 20x15mm", Type: "Split or Un-Split" },
    useCases: ["Machine tool wiring protection", "Robotic cable management", "Automotive cable routing", "Dynamic cable applications"],
    isFeatured: false,
    isActive: true,
    image: "/products/maxflex-polypropelene.png",
    cataloguePage: "/products/pages/catalogue-08.png",
  },

  // --- WIRING ACCESSORIES ---
  {
    _id: "prod-28",
    name: "Grommets - Standard, Diaphragm & Strips",
    slug: "grommets",
    sku: "GROM-STD",
    description: "PVC and nylon grommets for protecting cables passing through panel holes and sheet metal. Available as standard, diaphragm, and strip types. Wide range of sizes covering panel hole diameters from 6.4mm to 43mm. Natural and black colours.",
    category: fallbackCategories[10],
    specifications: { Material: "PVC / Nylon", Types: "Standard, Diaphragm, Strip", Colours: "Natural / Black", "Panel Hole Range": "6.4mm to 43mm" },
    useCases: ["Cable entry hole protection", "Sheet metal cable management", "Panel hole grommeting", "Vibration dampening"],
    isFeatured: false,
    isActive: true,
    image: "/products/grommets.png",
  },
  {
    _id: "prod-29",
    name: "Snap Bushings & Blanking Plugs",
    slug: "snap-bushings-blanking-plugs",
    sku: "BUSH-SNAP",
    description: "Nylon snap bushings and hole blanking plugs for clean cable entry and unused hole sealing in panels and enclosures. Snap bushings in miniature to 50.6mm sizes; blanking plugs from 6.4mm to 63.5mm diameter.",
    category: fallbackCategories[10],
    specifications: { Material: "Nylon", "Snap Bushing Range": "Miniature to 50.6mm", "Blanking Plug Range": "6.4mm to 63.5mm" },
    useCases: ["Unused hole blanking", "Cable entry protection", "Panel hole sealing", "Enclosure finishing"],
    isFeatured: false,
    isActive: true,
    image: "/products/snap-bushings.png",
  },
  {
    _id: "prod-30",
    name: "SUP Saddle Clip-In & Saddle Supports",
    slug: "sup-saddle-supports",
    sku: "SUP-SADDLE",
    description: "Nylon 6.6 saddle supports for press-fitting cables to panels and walls. SUP Saddle Clip-In inserts into a pre-drilled guide; SUP Saddle Support is used with screws. Self-extinguishing (V2) material. Suitable for 9mm cables and above.",
    category: fallbackCategories[10],
    specifications: { Material: "Nylon 6.6", "Flammability Rating": "V2", "Hole Depth": "4.5mm", "Leg Spread": "3.2mm", Types: "Clip-in / Screw-mount" },
    useCases: ["Cable saddle mounting", "Panel and wall cable fixing", "Cable run spacing", "Cable support at regular intervals"],
    isFeatured: false,
    isActive: true,
    image: "/products/sup-saddle-supports.png",
  },
  {
    _id: "prod-31",
    name: "Nylon Adhesive Cable Tie Bases",
    slug: "nylon-adhesive-bases",
    sku: "ADH-BASE",
    description: "Double-sided adhesive nylon cable tie bases for mounting cable ties on flat surfaces without drilling. Self-extinguishing material. Available in 13x13mm, 20x20mm, and 30x30mm sizes, accommodating tie widths up to 5.5mm.",
    category: fallbackCategories[10],
    specifications: { Material: "Nylon 9.5", "Flammability Rating": "Self-extinguishing", Sizes: "13x13mm, 20x20mm, 30x30mm", "Tie Width": "Up to 5.5mm", Adhesive: "Double-sided" },
    useCases: ["Adhesive cable tie mounting", "Surface cable management", "No-drill cable fixing", "Panel interior cable routing"],
    isFeatured: false,
    isActive: true,
    image: "/products/nylon-adhesive-bases.png",
  },

  // --- CABLE TIES (additional) ---
  {
    _id: "prod-32",
    name: "Three-D Cable Ties PA66",
    slug: "three-d-cable-ties-pa66",
    sku: "CT-3D-PA66",
    description: "Standard PA66 nylon cable ties in a range of sizes from 140x3.5mm to 500x12.5mm. UL94 V-2 rated, operating temperature -40°C to +85°C, minimum installation temperature -20°C. Certified to RU, UL, CE, ABS, BV, DNV, LloydEs, RoHS.",
    category: fallbackCategories[0],
    specifications: { Material: "PA66 (Nylon 66)", "Flammability Rating": "UL94V-2", "Operating Temp": "-40°C to +85°C", "Min Install Temp": "-20°C", Certification: "UL, CE, ABS, BV, DNV, LloydEs, RoHS", "Size Range": "140x3.5mm to 500x12.5mm" },
    useCases: ["General cable bundling", "Industrial panel wiring", "Outdoor cable management", "Bulk cable tie applications"],
    isFeatured: false,
    isActive: true,
    image: "/products/cable-ties-pa66.png",
  },
  {
    _id: "prod-33",
    name: "Nyloc Cable Ties",
    slug: "nyloc-cable-ties",
    sku: "CT-NYLOC",
    description: "Nyloc advanced nylon cable ties with patented design — 30% less raw material, thinner yet stronger. Rounded head and internal neck ensures minimal cable damage. Available in 100x1.8mm to 750x4.6mm. Standard and UV-stabilised variants.",
    category: fallbackCategories[0],
    specifications: { Material: "Nylon 6.6", "Size Range": "100x1.8mm to 750x4.6mm", Variants: "Standard (NYL) / UV (NYL-UV)", "Tensile Strength": "Up to 225N", "Operating Temp": "-40°C to +85°C" },
    useCases: ["Precision cable bundling", "Automotive wiring", "Thin cable applications", "UV-resistant outdoor use"],
    isFeatured: false,
    isActive: true,
    image: "/products/cable-ties-nyloc.png",
  },
  {
    _id: "prod-34",
    name: "UV Protected Nylon Cable Ties",
    slug: "uv-protected-cable-ties",
    sku: "CT-UV",
    description: "UV-protected self-extinguishing black nylon cable ties rated for 10-year outdoor lifespan. Temperature range -40°C to +85°C. Available in sizes from 100x2.5mm to 500x7.5mm. Working Life (C) = UV Protected for extreme outdoor durability.",
    category: fallbackCategories[0],
    specifications: { Material: "Black Nylon 6.6", "UV Protection": "10 Year Lifespan", "Operating Temp": "-40°C to +85°C", Colour: "Black", "Size Range": "100x2.5mm to 500x7.5mm" },
    useCases: ["Outdoor cable installations", "Solar panel cable management", "Street furniture wiring", "Marine and coastal applications"],
    isFeatured: false,
    isActive: true,
    image: "/products/cable-ties-uv.png",
  },
  {
    _id: "prod-35",
    name: "M.E.T. Nylon Cable Ties with Stainless Steel Tooth",
    slug: "met-cable-ties-stainless-tooth",
    sku: "CT-MET",
    description: "Sapiselco M.E.T. cable ties featuring a stainless steel tooth for superior grip. Designed for extreme environments (-40°C to +85°C). The steel tooth provides break-defined grip points for consistent tightening. Maximum flexibility combined with extreme strength.",
    category: fallbackCategories[0],
    specifications: { Material: "Nylon 6.6 with stainless steel tooth", "Operating Temp": "-40°C to +85°C", "Size Range": "100x3.5mm to 360x7.5mm", Feature: "Stainless steel locking tooth" },
    useCases: ["High-vibration cable securing", "Mining and construction", "Marine applications", "Extreme temperature environments"],
    isFeatured: false,
    isActive: true,
    image: "/products/cable-ties-met.png",
  },
  {
    _id: "prod-36",
    name: "DET Metal Detectable Cable Ties",
    slug: "det-metal-detectable-cable-ties",
    sku: "CT-DET",
    description: "Metal detectable nylon 6.6 cable ties with metal powder additive for detection in food, pharmaceutical, and chemical industries. Blue colour and X-ray detectable. Recommended maximum load no higher than 10% of work load.",
    category: fallbackCategories[0],
    specifications: { Material: "Nylon 6.6 with metal powder additive", Colour: "Blue", Detection: "Metal detector and X-ray detectable", "Size Range": "140x3.5mm to 280x4.8mm", Industry: "Food / Pharmaceutical / Chemical" },
    useCases: ["Food processing facilities", "Pharmaceutical manufacturing", "Chemical plants", "Safety-critical cable management"],
    isFeatured: false,
    isActive: true,
    image: "/products/cable-ties-det.png",
  },

  // --- STAINLESS STEEL ---
  {
    _id: "prod-37",
    name: "Stainless Steel Ball Lock Cable Ties 304 SS",
    slug: "ss-ball-lock-cable-ties",
    sku: "CT-SS-304",
    description: "Un-coated 304 stainless steel ball-lock cable ties for extreme environments. Tensioning tool D92134B available. Widths from 4.6mm to 12.7mm, lengths from 150mm to 440mm. Suitable for outdoor, marine, chemical, and high-temperature applications.",
    category: fallbackCategories[11],
    specifications: { Material: "304 Stainless Steel", Coating: "Un-Coated", "Width Range": "4.6mm to 12.7mm", "Length Range": "150mm to 440mm", Tool: "D92134B Cable tensioning tool" },
    useCases: ["Outdoor pole and structure cable fixing", "Marine cable bundling", "Chemical plant cable management", "High-temperature cable securing"],
    isFeatured: false,
    isActive: true,
    image: "/products/ss-cable-ties.png",
  },
  {
    _id: "prod-38",
    name: "304 SS Strapping - Light & Heavy Duty",
    slug: "ss-strapping",
    sku: "SS-STRAP",
    description: "304 stainless steel banding strapping for securing pipes, cables, and equipment to structures. Available in light duty (9.5mm, 12.7mm) and heavy duty (9.5mm, 12.7mm, 16mm, 19mm) widths. 0.55–0.7mm thickness, 30m rolls. RG1000 strapping tool available.",
    category: fallbackCategories[11],
    specifications: { Material: "304 Stainless Steel", Thickness: "0.55mm / 0.7mm", "Roll Length": "30m", "Width Range": "9.5mm to 19mm", Grades: "Light Duty / Heavy Duty", Tool: "RG1000 with built-in cutter" },
    useCases: ["Pipe and cable banding to poles", "Outdoor signage and fixture mounting", "Infrastructure cable management", "Industrial securing applications"],
    isFeatured: false,
    isActive: true,
    image: "/products/ss-strapping-heavy-duty.png",
  },
  {
    _id: "prod-39",
    name: "304 SS Buckles - Light & Heavy Duty",
    slug: "ss-buckles",
    sku: "SS-BUCKLE",
    description: "304 stainless steel buckles to complete banding installations with SS strapping. Available in light duty and heavy duty grades, widths 9.5mm, 12.7mm, 16mm, and 19mm. Sold in packs of 100.",
    category: fallbackCategories[11],
    specifications: { Material: "304 Stainless Steel", "Width Range": "9.5mm to 19mm", Grades: "Light Duty / Heavy Duty", "Pack Size": "100 pieces" },
    useCases: ["Strapping band closures", "Pole and pipe banding", "Outdoor fixture installation", "Infrastructure cable management"],
    isFeatured: false,
    isActive: true,
    image: "/products/ss-buckles.png",
  },

  // --- HEAT SHRINK (additional) ---
  {
    _id: "prod-40",
    name: "Heatshrink Tubing 2:1 Ratio",
    slug: "heatshrink-2to1",
    sku: "HS-2-1",
    description: "Halogen-free, flame-retardant polyolefin heat shrink tubing with 2:1 shrink ratio. Available in 7 colours (Black, Blue, Yellow/Green, Yellow, Red, Green, White) and sizes from Ø1.6mm to Ø90mm. Operating temperature -40°C to +125°C. Meets ASTM D2671.",
    category: fallbackCategories[1],
    specifications: { Material: "Polyolefin", "Shrink Ratio": "2:1", "Size Range": "Ø1.6mm to Ø90mm", Colours: "Black, Blue, Yellow/Green, Yellow, Red, Green, White", "Operating Temp": "-40°C to +125°C", Compliance: "ASTM D2671, UL 224" },
    useCases: ["Cable insulation and protection", "Colour coding", "Solder joint protection", "Strain relief"],
    isFeatured: false,
    isActive: true,
    image: "/products/heatshrink-2to1.png",
  },
  {
    _id: "prod-41",
    name: "Heatshrink Dual Wall 3:1 Ratio",
    slug: "heatshrink-dual-wall-3to1",
    sku: "HS-DW-3-1-THICK",
    description: "Very flexible dual-wall heat shrink tubing with adhesive inner layer. Outer: cross-linked modified polyolefin; Inner: hot-melt adhesive. 3:1 shrink ratio. Provides waterproof seal for cable joints, terminations, and connector protection. Black only.",
    category: fallbackCategories[1],
    specifications: { "Outer Material": "Cross-linked modified polyolefin", "Inner Layer": "Hot-melt adhesive", "Shrink Ratio": "3:1", Colour: "Black", "Size Range": "3.2mm to 40mm", "Waterproof": "Yes (adhesive seal)" },
    useCases: ["Waterproof cable terminations", "Underground cable joints", "Marine and outdoor wiring", "Connector strain relief"],
    isFeatured: false,
    isActive: true,
    image: "/products/heatshrink-dual-wall.png",
  },
  {
    _id: "prod-42",
    name: "Heatshrink Medium Wall 3.5:1 / 4:1 Ratio",
    slug: "heatshrink-medium-wall",
    sku: "HS-MW",
    description: "Medium wall heat shrink tubing with inner polyamide adhesive layer. Available in 3.5:1 and 4:1 shrink ratios. Single wire end sleeve inner layer provides excellent insulation and mechanical protection. Black only, operating up to 135°C.",
    category: fallbackCategories[1],
    specifications: { Material: "Cross-linked polyolefin", "Inner Layer": "Polyamide adhesive", "Shrink Ratio": "3.5:1 / 4:1", Colour: "Black", "Size Range": "8mm to 76mm", "Operating Temp": "Up to 135°C" },
    useCases: ["Medium voltage cable protection", "Busbar insulation", "Heavy cable joint protection", "High mechanical stress applications"],
    isFeatured: false,
    isActive: true,
    image: "/products/heatshrink-medium-wall.png",
  },

  // --- FERRULES & TERMINALS ---
  {
    _id: "prod-43",
    name: "End Caps",
    slug: "end-caps",
    sku: "END-CAPS",
    description: "Black heat-shrinkable end caps for sealing cable ends against moisture and contaminants. Excellent water resistance and chemical resistance for power cables. Available sizes GEC01 (12mm) to GEC401 (100mm), cable range 2.5 to 60mm².",
    category: fallbackCategories[3],
    specifications: { Material: "Heat-shrink", Colour: "Black", Resistance: "Water and chemical resistant", "Size Range": "GEC01 to GEC401", "Cable Range": "2.5mm² to 60mm²" },
    useCases: ["Cable end sealing", "Power cable termination", "Moisture protection", "Underground cable ends"],
    isFeatured: false,
    isActive: true,
    image: "/products/end-caps.png",
  },
  {
    _id: "prod-44",
    name: "Copper Flat Pins & Ferrules",
    slug: "copper-flat-pins-ferrules",
    sku: "CU-FLAT-PINS",
    description: "Copper cable flat pins and ferrules for power cable terminations. Available in a comprehensive range of conductor sizes from 1.5mm² to 630mm².",
    category: fallbackCategories[3],
    specifications: { Material: "Copper", "Size Range": "1.5mm² to 630mm²", Type: "Flat pins and ferrules" },
    useCases: ["Power cable terminations", "Busbar connections", "Switchgear terminations", "MV and LV cable connections"],
    isFeatured: false,
    isActive: true,
    image: "/products/copper-flat-pins-ferrules.png",
  },
  {
    _id: "prod-45",
    name: "XLPE Lugs",
    slug: "xlpe-lugs",
    sku: "XLPE-LUGS",
    description: "XLPE cable lugs for terminating XLPE insulated cables. Available from 35mm² to 630mm², with blank or standard stud options. All dimensions in mm. SABS IEC 61238 tested.",
    category: fallbackCategories[3],
    specifications: { Material: "Copper / XLPE", "Size Range": "35mm² to 630mm²", Testing: "SABS IEC 61238", Type: "XLPE cable lugs" },
    useCases: ["XLPE cable terminations", "MV switchgear connections", "Transformer terminations", "Power distribution terminations"],
    isFeatured: false,
    isActive: true,
    image: "/products/xlpe-lugs.png",
  },
  {
    _id: "prod-46",
    name: "XLPE Ferrules",
    slug: "xlpe-ferrules",
    sku: "XLPE-FER",
    description: "XLPE cable ferrules for joining and connecting XLPE insulated cables. Available from 25mm² to 630mm². Dimensions in mm. Suitable for medium and low voltage XLPE cable connections.",
    category: fallbackCategories[3],
    specifications: { Material: "Copper / XLPE", "Size Range": "25mm² to 630mm²", Type: "XLPE ferrules" },
    useCases: ["XLPE cable jointing", "Power cable connections", "Underground cable joints", "MV cable infrastructure"],
    isFeatured: false,
    isActive: true,
    image: "/products/xlpe-ferrules.png",
  },
  {
    _id: "prod-47",
    name: "Copper Lugs - SABS IEC 61238 Tested",
    slug: "copper-lugs",
    sku: "CU-LUGS",
    description: "SABS IEC 61238 tested copper cable lugs for reliable power cable terminations. Comprehensive range from 1.5mm² to 1000mm² in various stud sizes and blank configurations. All dimensions in mm unless indicated otherwise.",
    category: fallbackCategories[3],
    specifications: { Material: "Copper", Testing: "SABS IEC 61238", "Size Range": "1.5mm² to 1000mm²", Type: "Copper cable lugs", Stud: "Various / Blank" },
    useCases: ["LV and MV cable terminations", "Switchgear connections", "Bus bar connections", "Generator and transformer connections"],
    isFeatured: true,
    isActive: true,
    image: "/products/copper-lugs.png",
  },
  {
    _id: "prod-48",
    name: "Aluminium Terminals - Round",
    slug: "aluminium-terminals-round",
    sku: "AL-TERM-RND",
    description: "Aluminium round cable terminals for aluminium conductor connections. Finish: Natural / Passivated Aluminium. Available from 10mm² to 300mm² with standard stud sizes.",
    category: fallbackCategories[3],
    specifications: { Material: "Aluminium", Finish: "Natural / Passivated", "Size Range": "10mm² to 300mm²", Type: "Round terminals" },
    useCases: ["Aluminium cable terminations", "Overhead line connections", "Distribution transformer connections", "LV panel terminations"],
    isFeatured: false,
    isActive: true,
    image: "/products/aluminium-terminals-round.png",
  },
  {
    _id: "prod-49",
    name: "Aluminium 4 Core Sector Cable Lugs",
    slug: "aluminium-4core-sector-lugs",
    sku: "AL-4CORE-LUG",
    description: "Aluminium 4 core sector cable lugs for sector-shaped conductor terminations. Available in 25mm² to 300mm² with 4-core sector configuration. All dimensions in mm.",
    category: fallbackCategories[3],
    specifications: { Material: "Aluminium", Configuration: "4-Core Sector", "Size Range": "25mm² to 300mm²" },
    useCases: ["4-core aluminium cable terminations", "LV distribution cable connections", "Overhead cable joints", "Underground cable terminations"],
    isFeatured: false,
    isActive: true,
    image: "/products/aluminium-4core-lugs.png",
  },
  {
    _id: "prod-50",
    name: "Aluminium 3 Core Sector Cable Lugs",
    slug: "aluminium-3core-sector-lugs",
    sku: "AL-3CORE-LUG",
    description: "Aluminium 3 core sector cable lugs for sector-shaped 3-core conductor terminations. Available in 25mm² to 300mm². All dimensions in mm unless indicated otherwise.",
    category: fallbackCategories[3],
    specifications: { Material: "Aluminium", Configuration: "3-Core Sector", "Size Range": "25mm² to 300mm²" },
    useCases: ["3-core aluminium cable terminations", "3-phase distribution connections", "Underground cable terminations", "LV switchgear connections"],
    isFeatured: false,
    isActive: true,
    image: "/products/aluminium-3core-lugs.png",
  },
  {
    _id: "prod-51",
    name: "Pre-Insulated Terminals",
    slug: "pre-insulated-terminals",
    sku: "PRE-INS-TERM",
    description: "Pre-insulated crimp terminals for secure and colour-coded wire connections. Includes ring, fork, pin, bullet, and flag types. Available in red (0.5–1.5mm²), blue (1.5–2.5mm²), and yellow (4–6mm²) colour coding. Double grip variants available.",
    category: fallbackCategories[3],
    specifications: { Sizes: "0.5mm² to 6mm²", Colours: "Red (0.5–1.5mm²), Blue (1.5–2.5mm²), Yellow (4–6mm²)", Types: "Ring, Fork, Pin, Bullet, Flag, Double Grip" },
    useCases: ["Panel wiring terminations", "Control system wiring", "Switchboard connections", "Automotive wiring"],
    isFeatured: true,
    isActive: true,
    image: "/products/pre-insulated-terminals.png",
  },
  {
    _id: "prod-52",
    name: "Single Wire End Sleeves (Boot Lace Ferrules)",
    slug: "single-wire-end-sleeves",
    sku: "END-SLEEVES",
    description: "Colour-coded insulated single wire end sleeves (boot lace ferrules) for professional termination of stranded conductors. Available in sizes 0.25mm² to 50mm², multiple colours per DIN standard. Length 10mm (standard) per item.",
    category: fallbackCategories[3],
    specifications: { "Size Range": "0.25mm² to 50mm²", Colours: "DIN colour-coded", Length: "10mm standard", Material: "Copper barrel with insulated collar", Standard: "DIN 46228" },
    useCases: ["Stranded conductor terminations", "PLC and control panel wiring", "DIN rail terminal blocks", "VFD and relay wiring"],
    isFeatured: true,
    isActive: true,
    image: "/products/end-sleeves.png",
  },

  // --- CABLE GLANDS (additional) ---
  {
    _id: "prod-53",
    name: "Patrax Cable Glands - Brass Nickel Plated",
    slug: "patrax-cable-glands-brass",
    sku: "CG-PATRAX-BW",
    description: "Die-cast Rotary Nickel plated brass cable glands for armoured (BW) and un-armoured (A2) cable types. Available in sizes 0 to 7 (BW Type) and 00 (28mm) to 7 (A2 Type). PVC shrouds available. Suitable for industrial and hazardous area installations.",
    category: fallbackCategories[4],
    specifications: { Material: "Nickel plated brass", Types: "BW Type Glands / A2 Type Glands", Sizes: "0 to 7", Accessories: "PVC Shrouds (1–8)", Application: "Armoured and un-armoured cables" },
    useCases: ["Armoured cable gland terminations", "Industrial panel cable entry", "Hazardous area installations", "Mining and petrochemical applications"],
    isFeatured: true,
    isActive: true,
    image: "/products/patrax-glands.png",
  },
  {
    _id: "prod-54",
    name: "Nylon Cable Glands & Lock Nuts",
    slug: "nylon-cable-glands",
    sku: "CG-NYLON",
    description: "M20 nylon 98 cable glands and lock nuts for standard cable entry applications. Available in Light Grey and Black. Cable glands: M20 thread in 10mm, 15mm, and 25mm cable ranges. Lock nuts M20 in grey and black.",
    category: fallbackCategories[4],
    specifications: { Material: "Nylon 98", Thread: "M20", Colours: "Light Grey / Black", "Cable Ranges": "M20x1.5: 6–12mm, M20x10: various", Includes: "Lock nuts available separately" },
    useCases: ["Junction box cable entry", "Control panel wiring", "General purpose cable glands", "Light industrial enclosure entry"],
    isFeatured: true,
    isActive: true,
    image: "/products/nylon-glands.png",
  },
];
